version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm i
      - run: npm test
      - run: echo "Tested successfully"
workflows:
  version: 2
  run_test:
    jobs:
      - test
